name: Build application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: build