name: Build/Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Initialize Environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Dependencies
        run: yarn

      - name: Clean node_modules
        run: npx modclean -r

      - name: Build Application
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: streamoverlay.exe
          path: build/streamoverlay-*.exe