name: Build/Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install deps
        run: yarn

      - name: Rebuild addon
        run: yarn rebuild

      - name: Clean node_modules
        run: npx modclean -r

      - name: Build application
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}